# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d1c4d7103749a616be3483f079f6b8850cf2671fecd13f52842892ece734cebda490c10037f05931a1fdf0d8b740d02d7102674e0f0f5d713be85556e5061bb

test:
  secret_key_base: e35fd4b89def8b3eecc68fda2592043025ec5966043be2fa091f7f1eaf5fb500e524723b76aaf360d3948665239fa2424bf3c8755b2ef063ce8a4e9c1e6ae712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
